# -*- mode: python ; coding: utf-8 -*-
import os

block_cipher = None

# Add unp4k.exe and dependencies as data files
added_files = [
    ('unp4k.exe', '.'),
    ('*.dll', '.'),
    ('x64', 'x64'),
]

# Add x86 folder only if it exists (optional)
if os.path.exists('x86'):
    added_files.append(('x86', 'x86'))

a = Analysis(
    ['extract_tool.py'],
    pathex=[],
    binaries=[],
    datas=added_files,
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='SC_GlobalIni_Extractor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # No console window
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,  # Add icon file here if you have one
    version='version_info.txt',  # Version info for EXE Details tab (generated by GitHub Actions)
)
